### ISSUE TITLE
In app "Settings" button does not open uno's settings app

### ISSUE THREAD

**Issue by sasakrsmanovic** [unoplatform/studio#43]
### Current behavior

Reported here 
https://github.com/unoplatform/uno/discussions/18833#discussioncomment-11597605 

User cannot click on 'SETTINGS' 

![image](https://github.com/user-attachments/assets/20e35b08-7522-40a0-bde8-7fe1fb0a4554)

### Expected behavior

User can open settings and log on 

### Which tool(s) are affected?

Hot Design™, Hot Reload

**Comment by dr1rrb** [comment]
Hey @xperiandri could you give us more information about your issue:

1. Which IDE are you using (Visual Studio, VS Code, Rider ?)
2. Did you run uno-check? Does everything is green ? https://platform.uno/docs/articles/external/uno.check/doc/using-uno-check.html
3. Do you have the latest version of the uno-platform extension installed in your IDE?
4. Could you send us the log of your application?
5. With your app started, could you send us the content of the "uno platform" output window **in verbose mode**
   _(To get it in verbose in VisualStudio: Go to Tools > Options > Projects and Solutions, set MSBuild project output verbosity to Diagnostic, restart visual studio)_

Thanks you for your help

**Comment by xperiandri** [comment]
1. Visual Studio 2022 17.12.3 and VS Code on Mac
2. Yes

**Comment by xperiandri** [comment]
@VolodymyrZaburmekha

**Comment by DevTKSS** [comment]
@sasakrsmanovic @xperiandri actually yesterday I have gotten a similar thing on my first uno HotReload app (wanted to add something) and it was showing also way more laggyness (the app) and not the hotDesogn icon i seen there before.

 so I would like to share some details for you to inspect for matching:
- Is Desktop the ONE AND ONLY Target on this app?
No? Do create one, using recommended "uno plattform app" template in vs studio, mvux and xaml. Does that work?
- Do you have this issue only on the existing App or also if you do a new one?
- Did you upload this repo on github deleted the local files and downloaded it again?
Please do in this case also a new one that started this missing Studio issue for this application beside the strange banner.

**Comment by dr1rrb** [comment]
@xperiandri Are you able to share some logs with us, especially those coming from the "Uno Platfrom" output? (With "Diagnostic" verbosity, don't forget to restart VS after enabling it)

![image](https://github.com/user-attachments/assets/de07a0d9-4055-42fe-a2af-836ca5b9ed92)

Thank you

**Comment by dr1rrb** [comment]
@DevTKSS This is interesting, did you face some cases where you had to do all of this to get the settings button to work? Are you able to find a scenario where you repro this "settings button not working" which is solved by doing those tricks?

**Comment by DevTKSS** [comment]
@dr1rrb Reading and seeing your screenshot... Never done anything there in my visual studio... Should I do that? Not knowing much about msbuild...
To the repro...
What I did get to work has been, removing the additional window target at least has let me get the login back to recognized, but the studio button was still missing AND this app has got +1000% more laggy than before uploading to github and cloning back to my local maschine, thats why i decided to port the content to my new app with only desktop target. The big differences has been the Windows target, which has been not build to just included! No HotReload or studio button had shown up as i just tried to build towards it where i was stunned it had no issue because of the anycpu which has been an issue before. But as said, beside it has build no uno advantages usable only seen the live tree in an uno app then first time, which is not showing in desktop target.
Hm... Yes, so desktop target only, than the current uno.sdk version think it is 5.56? The other bad one has had a minor one like 54 or 53. Using recommended template... Learned how to get binding working(not x:bind) from studio 😁 but its not able to fill navigation propertys at this point....

Ah! And if you have any komments added in your code of xaml, delete it, the engine do read komments🤣 crazy things happened catched on video but not had the time to polish it up and/or push it up into my onedrive, sorry. And GitHub is not allowing me to invite someone to a currently private repo or change the modifyer with my not desktop device🥴 than you could clone it and see yourself. But its not explicitly a small repo its just pushed up and since the described issues and porting the content i am not planning do fixes on it.

**Comment by nickrandolph** [comment]
@DevTKSS thanks for the feedback - beyond the issue pertaining to the settings button, can you please log separate issues relating to what you're seeing for x:Bind, Navigation properties and xaml comments. We have some known issues with the x:Bind path picker; Navigation properties should be available (but you need to make sure Navigation is added to your application) and xaml comments should be supported (so raise an issue if this isn't the case).

**Comment by DevTKSS** [comment]
x:Bind is known to be not currently working properly for Binding to viewModel in mvux especially, coming from sourcegenerators can not depend on each other. For some a workaround is working but to me not, getting NullReferenceException as soon as i bind a command just only OneTime.
I can not tell the explicit issue number because there are so many made for this. Its a Microsoft issue also. but to me thats a good reason why the engine would not give me the opportunity to use it when using mvux. Did not search for issue listed to that, not enough time on my side. Have to restart the application &studio if i clicked on x:bind, its hanging then.

**Comment by VolodymyrZaburmekha** [comment]
Hi,  @dr1rrb, sorry for a late reply, here are some answers, that @xperiandri didn't provide
> 4. Could you send us the log of your application?

Do you mean log from "Debug Console" or Terminal or both?

> 5. With your app started, could you send us the content of the "uno platform" output window **in verbose mode**
>    _(To get it in verbose in VisualStudio: Go to Tools > Options > Projects and Solutions, set MSBuild project output verbosity to Diagnostic, restart visual studio)_

I'm using VS Code on Mac, not sure how to provide exactly what you described for Visual Studio.
Here is the output from the Uno Platform
```
[Info] Launching XAML language server /Users/admin/.vscode/extensions/unoplatform.vscode-0.18.5/bin/lshost/net9.0/Uno.LSP.Host.dll
[Info] Found 'ms-dotnettools.csharp' version 2.55.29.
[Info] Found 'ms-dotnettools.csdevkit' version 1.14.14.
[Info] Found 'ms-dotnettools.dotnet-maui' version 1.6.16.
[Info] C# extension onServerStateChange API is available.
[Info] Running in Dev Kit mode
[Info] Uno Platform "dotnet new" templates are already installed. The templates may be updated by running "dotnet new install Uno.Templates"
[Info] Setting active project /Users/admin/Projects/ecierge/PropertyManagement/Console/App/Console.App.csproj
```

Here is the output from Uno Platform - Hot Reload
```
[Info] Launching remote control server (Port:57961, Path:/Users/admin/.nuget/packages/uno.winui.devserver/5.5.87/buildTransitive/../tools/rc/host/net9.0/Uno.UI.RemoteControl.Host.dll)
warn: Uno.UI.RemoteControl.Host.Extensibility.AddIns[0]
      Failed to get target frameworks of solution '/Users/admin/Projects/ecierge/PropertyManagement/eCierge.sln'. This usually indicates that the solution is in an invalid state (e.g. a referenced project is missing on disk). Please fix and restart your IDE (command used: `dotnet build "/Users/admin/Projects/ecierge/PropertyManagement/eCierge.sln" --target:UnoDumpTargetFrameworks "-p:UnoDumpTargetFrameworksTargetFile=/var/folders/vj/9t3c5b6d53s7r59gpkqry3hh0000gn/T/tmp412eFh.tmp" --verbosity quiet`).

dbug: Microsoft.AspNetCore.Hosting.Diagnostics[3]
      Hosting starting

dbug: Microsoft.AspNetCore.Hosting.Diagnostics[4]
      Hosting started

dbug: Microsoft.AspNetCore.Hosting.Diagnostics[13]
      Loaded hosting startup assembly Uno.UI.RemoteControl.Host

Hosting environment: Production
Content root path: /Users/admin/Projects/ecierge/PropertyManagement
Now listening on: http://[::]:57961
Application started. Press Ctrl+C to shut down.

dbug: Uno.UI.RemoteControl.Host.IdeChannel.IdeChannelServer[0]
      IDE Connected

dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[39]
      Connection id "0HN901V0SGDJR" accepted.

dbug: Microsoft.AspNetCore.Server.Kestrel.Connections[1]
      Connection id "0HN901V0SGDJR" started.

info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://localhost:57961/rc - - -

dbug: Microsoft.AspNetCore.Routing.RouteBase[1]
      Request successfully matched the route with name '(null)' and template 'rc'

info: Microsoft.AspNetCore.Builder.IApplicationBuilder[0]
      Accepted connection from ::ffff:127.0.0.1

dbug: Uno.UI.RemoteControl.Host.RemoteControlServer[0]
      Starting RemoteControlServer
```
If I create a new project from the template, hot reload works just fine and it doesn't ask me to sign in

**Comment by dr1rrb** [comment]
Hey @VolodymyrZaburmekha thanks for the logs. If you are using VS code, the most important output in our case is the "Uno Platform - Hot Reload" (and there is no additional steps to enable the verbose logging), so in the log you sent there is an interesting line:

```
Failed to get target frameworks of solution '/Users/admin/Projects/ecierge/PropertyManagement/eCierge.sln'. This usually indicates that the solution is in an invalid state (e.g. a referenced project is missing on disk). Please fix and restart your IDE (command used: `dotnet build "/Users/admin/Projects/ecierge/PropertyManagement/eCierge.sln" --target:UnoDumpTargetFrameworks "-p:UnoDumpTargetFrameworksTargetFile=/var/folders/vj/9t3c5b6d53s7r59gpkqry3hh0000gn/T/tmp412eFh.tmp" --verbosity quiet`)
```

When uno's "dev-server" starts (a helper process which detects files changes on disk to trigger hot-reload), we build your solution to determine few information like target frameworks, but here it failed to do so. Usually it's because your solution is in an invalid state.

Could you open a console, navigate to the solution's folder (`/Users/admin/Projects/ecierge/PropertyManagement/`) and run the command:

```
dotnet build "/Users/admin/Projects/ecierge/PropertyManagement/eCierge.sln" --target:UnoDumpTargetFrameworks "-p:UnoDumpTargetFrameworksTargetFile=/Users/admin/Projects/ecierge/PropertyManagement/target-frameworks.txt"
```

And then send us the output of the command and the content of the file "/Users/admin/Projects/ecierge/PropertyManagement/target-frameworks.txt" ?

**Comment by dr1rrb** [comment]
Also @VolodymyrZaburmekha  and @DevTKSS : a new version of the SDK [5.5.56](https://www.nuget.org/packages/Uno.Sdk/5.5.56) has been published yesterday, it might fix your issues. Please make sure to update first, thanks.

**Comment by sasakrsmanovic** [comment]
any luck @VolodymyrZaburmekha @DevTKSS  with the new SDK?

**Comment by DevTKSS** [comment]
New release? Actually i did not get time to proceed till now

**Comment by VolodymyrZaburmekha** [comment]
@sasakrsmanovic, @dr1rrb 
I tried the new SDK, unfortunately, it didn't fix the problem

I guess, the problem might be related to how uno handles solution filter files (`.slnf`) files. 

At least on my machine, the solution file(`.sln`) that Uno is trying to use is failing to build. This solution file also contains projects that are not required for building the Uno app.
Because there are a lot of projects there, we also have a `.slnf` file which is linked to the broken `.sln` file and intended to filter out not-needed projects and speed up project loading.

The build of the `.slnf` file is successful, the build of `.sln` is not.

In VS Code I open the `.slnf` file, but in the HotReload logs there is info only about the solution file and there is no info about the solution filter file,  so I guess it doesn't take into consideration the `.slnf` file.

Will try to fix this `.sln` file and check again

Here is the content of `target-frameworks.txt`:
```
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-windows10.0.26100
net9.0
net9.0-android
net9.0-ios
net9.0-maccatalyst
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-browserwasm
net9.0-android
net9.0-ios
net9.0-maccatalyst
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-browserwasm
net9.0-android
net9.0-ios
net9.0-maccatalyst
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-browserwasm
net9.0-desktop
net9.0-desktop
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-android
net9.0-ios
net9.0-maccatalyst
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-browserwasm
net9.0-android
net9.0-ios
net9.0-maccatalyst
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-browserwasm
net9.0-android
net9.0-ios
net9.0-maccatalyst
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-browserwasm
net9.0-desktop
net9.0-desktop
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-desktop
net9.0-android
net9.0-ios
net9.0-maccatalyst
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-browserwasm
net9.0-android
net9.0-ios
net9.0-maccatalyst
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-browserwasm
net9.0-android
net9.0-ios
net9.0-maccatalyst
net9.0-windows10.0.26100
net9.0
net9.0-desktop
net9.0-browserwasm
```
Thanks

**Comment by xperiandri** [comment]
Nothing there. 5.5.56 no effect

This is our log
```
The specified framework 'Microsoft.WindowsDesktop.App' is not present in the previously loaded runtime.
dbug: Uno.Extensions.Hosting.Internal.Host[0]
      Hosting starting
dbug: Uno.Extensions.Configuration.ReloadService[0]
      .ctor - Created
dbug: Uno.Extensions.Configuration.ReloadService[0]
      StartAsync - Application data path is 'C:\Users\Andrii\AppData\Local\Ecierge Software Development Inc.\Ecierge.Console\LocalState\config'
info: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.keyvaluestorageconfiguration.json' does not exist in package
info: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.serveroptions.json' does not exist in package
info: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.localizationconfiguration.json' does not exist in package
info: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.localizationsettings.json' does not exist in package
info: Uno.Extensions.Storage.FileStorage[0]
      ReadPackageFileAsync - File 'appsettings.navigationoptions.json' does not exist in package
dbug: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Reloading configuration - started
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Config provider of type 'ChainedConfigurationProvider'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Config provider of type 'EnvironmentVariablesConfigurationProvider'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Config provider of type 'JsonConfigurationProvider'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Loading from file 'appsettings.KeyValueStorageConfiguration.json'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - File doesn't exist 'C:\Users\Andrii\AppData\Local\Ecierge Software Development Inc\Ecierge.Console\LocalState\config\appsettings.KeyValueStorageConfiguration.json'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Config provider of type 'JsonStreamConfigurationProvider'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Config provider of type 'JsonStreamConfigurationProvider'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Config provider of type 'JsonConfigurationProvider'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Loading from file 'appsettings.ServerOptions.json'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - File doesn't exist 'C:\Users\Andrii\AppData\Local\Ecierge Software Development Inc\Ecierge.Console\LocalState\config\appsettings.ServerOptions.json'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Config provider of type 'JsonConfigurationProvider'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Loading from file 'appsettings.LocalizationConfiguration.json'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - File doesn't exist 'C:\Users\Andrii\AppData\Local\Ecierge Software Development Inc\Ecierge.Console\LocalState\config\appsettings.LocalizationConfiguration.json'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Config provider of type 'JsonConfigurationProvider'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Loading from file 'appsettings.LocalizationSettings.json'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - File doesn't exist 'C:\Users\Andrii\AppData\Local\Ecierge Software Development Inc\Ecierge.Console\LocalState\config\appsettings.LocalizationSettings.json'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Config provider of type 'JsonConfigurationProvider'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Loading from file 'appsettings.NavigationOptions.json'
trce: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - File doesn't exist 'C:\Users\Andrii\AppData\Local\Ecierge Software Development Inc\Ecierge.Console\LocalState\config\appsettings.NavigationOptions.json'
dbug: Uno.Extensions.Configuration.ReloadService[0]
      ReloadAllFileConfigurationProviders - Reloading configuration complete
dbug: Uno.Extensions.Configuration.ReloadService[0]
      StartAsync - Startup completed
dbug: Uno.Extensions.Hosting.Internal.Host[0]
      Hosting started
dbug: Uno.UI.Xaml.Controls.BaseWindowImplementation[0]
      Window visibility changing to True
dbug: Uno.UI.Runtime.Skia.Wpf.Rendering.WpfRendererProvider[0]
      Validating  rendering
trce: Uno.UI.Runtime.Skia.Wpf.Rendering.OpenGLWpfRenderer[0]
      OpenGL Version: 4.6.14802 Compatibility Profile Context 21.40.18.15 30.0.14018.15002
dbug: Uno.UI.Xaml.Controls.BaseWindowImplementation[0]
      Window activating with PointerActivated state.
dbug: Windows.UI.Core.CoreWindow[0]
      CoreWindow activating with PointerActivated state.
dbug: Uno.UI.HotDesign.MessageBroker[0]
      Registering handler: 'RemoteControlService (LicenseResponseMessage)'
dbug: Uno.UI.Xaml.Controls.BaseWindowImplementation[0]
      Window activating with CodeActivated state.
dbug: Windows.UI.Core.CoreWindow[0]
      CoreWindow activating with CodeActivated state.
trce: Uno.Toolkit.UI.ExtendedSplashScreen[0]
      Attempting to load manifest `AppxManifest.xml` from file packaged with application.
trce: Uno.Toolkit.UI.ExtendedSplashScreen[0]
      Full path to AppxManifest.xml is C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\bin\Debug\net8.0-desktop\AppxManifest.xml.
dbug: Uno.Toolkit.UI.ExtendedSplashScreen[0]
      The manifest `AppxManifest.xml` exists as a packaged file but could not be loaded to XDocument: System.IO.FileNotFoundException: Could not find file 'C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\bin\Debug\net8.0-desktop\AppxManifest.xml'.
      File name: 'C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\bin\Debug\net8.0-desktop\AppxManifest.xml'
         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
         at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
         at System.Xml.XmlTextReaderImpl.FinishInitUriString()
         at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
         at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
         at Uno.Toolkit.UI.ExtendedSplashScreen.LoadManifestFromPackageFile(Assembly entry, String manifestFile).
trce: Uno.Toolkit.UI.ExtendedSplashScreen[0]
      Attempting to load manifest from embedded resource `AppxManifest.xml` within the Ecierge.Console assembly.
trce: Uno.Toolkit.UI.ExtendedSplashScreen[0]
      Attempting to load manifest `package.appxmanifest` from file packaged with application.
trce: Uno.Toolkit.UI.ExtendedSplashScreen[0]
      Full path to package.appxmanifest is C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\bin\Debug\net8.0-desktop\package.appxmanifest.
dbug: Uno.Toolkit.UI.ExtendedSplashScreen[0]
      The manifest `package.appxmanifest` exists as a packaged file but could not be loaded to XDocument: System.IO.FileNotFoundException: Could not find file 'C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\bin\Debug\net8.0-desktop\package.appxmanifest'.
      File name: 'C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\bin\Debug\net8.0-desktop\package.appxmanifest'
         at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
         at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.Strategies.FileStreamHelpers.ChooseStrategyCore(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
         at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
         at System.Xml.XmlDownloadManager.GetStream(Uri uri, ICredentials credentials, IWebProxy proxy)
         at System.Xml.XmlTextReaderImpl.FinishInitUriString()
         at System.Xml.XmlReaderSettings.CreateReader(String inputUri, XmlParserContext inputContext)
         at System.Xml.Linq.XDocument.Load(String uri, LoadOptions options)
         at Uno.Toolkit.UI.ExtendedSplashScreen.LoadManifestFromPackageFile(Assembly entry, String manifestFile).
trce: Uno.Toolkit.UI.ExtendedSplashScreen[0]
      Attempting to load manifest from embedded resource `package.appxmanifest` within the Ecierge.Console assembly.
dbug: Uno.Toolkit.UI.SafeArea[0]
      WindowInsets=[Thickness: 0-0-0-0] bounds=0,0,1011.2000122070312,604.7999877929688 visibleBounds=0,0,1011.2000122070312,604.7999877929688
dbug: Uno.UI.Xaml.Input.FocusRectManager[0]
      Hiding focus rect
dbug: CommunityToolkit.WinUI.Lottie.LottieVisualSourceBase[0]
      Version: 5.5.7 Duration: 00:00:04.6666665 Fps:30 InPoint: 0 OutPoint: 140
dbug: Uno.Toolkit.UI.SafeArea[0]
      WindowInsets=[Thickness: 0-0-0-0] bounds=0,0,1011.2000122070312,604.7999877929688 visibleBounds=0,0,1011.2000122070312,604.7999877929688
dbug: Elmish.Uno.Performance[0]
      [main] updateViewModel (11ms):
dbug: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
      ProjectConfigurationAttribute=C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\Console.App.csproj, Paths=59
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\Presentation
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\Models
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\Options
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\Platforms\Desktop
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\Serialization
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\Services\Caching
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\Services\Endpoints
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\obj\Debug\net8.0-desktop
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\obj\Debug\net8.0-desktop\unoresizetizer
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Components
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Dialogs
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Layouts
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Presentation
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Presentation\Assets
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Presentation\Assets\Types
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Presentation\Assets\Types\Digital
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Presentation\Building
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Presentation\MakesAndModels
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\Navigation
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\TemplateSelectors
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Construction\obj\Debug\net8.0-desktop
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Management\Components
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Management\Dialogs
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Management\Presentation
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Management
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Management\Navigation
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\Management\obj\Debug\net8.0-desktop
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Components
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Controls
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Dialogs
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Presentation
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Presentation\EditStaffMember
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Styles
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Themes
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Behaviors
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Converters
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Markup
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Navigation
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\Uno
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\UI\obj\Debug\net8.0-desktop
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Controls
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Controls\Themes
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Controls\Behaviors
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Controls\obj\Debug\net8.0-desktop
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation\UI
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation\AttachedProperties
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation\Extensions
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation\NavigationScope
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation\Navigation
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation\Navigators
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation\Routing
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation\SystemIntegration
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\Ecierge.Uno.Navigation\obj\Debug\net8.0-desktop
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\OpenIddict.Client.UnoTokenPersistence
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
        - C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.Uno\OpenIddict.Client.UnoTokenPersistence\obj\Debug\net8.0-desktop
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
      ServerMetadataUpdates Enabled:False DebuggerAttached:True BuildingInsideVS: True unorid: Skia
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
      Partial Hot Reload Enabled:False unoRuntimeIdentifier:Skia targetFramework:net8.0-desktop buildingInsideVisualStudio:net8.0-desktop debuggerAttached:True IsIssue93860Fixed:False
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
      XamlReader Hot Reload Enabled:False targetFramework:net8.0-desktop
trce: Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor[0]
      Metadata Updates runtime capabilities: Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters GenericUpdateMethod GenericAddMethodToExistingType GenericAddFieldToExistingType
trce: Uno.UI.HotDesign.MessageBroker.MessageBrokerRegistration[0]
      RemoteControlService sending message: 'ProcessorsDiscovery'
trce: Uno.UI.HotDesign.MessageBroker.MessageBrokerRegistration[0]
      RemoteControlService sending message: 'AnalyticsEventMessage'
dbug: Uno.Toolkit.UI.SafeArea[0]
      WindowInsets=[Thickness: 0-0-0-0] bounds=0,0,1011.2000122070312,604.7999877929688 visibleBounds=0,0,1011.2000122070312,604.7999877929688
dbug: Uno.Toolkit.UI.SafeArea[0]
      WindowInsets=[Thickness: 0-0-0-0] bounds=0,0,1011.2000122070312,604.7999877929688 visibleBounds=0,0,1011.2000122070312,604.7999877929688
warn: Uno.UI.HotDesign.MessageBroker[0]
      Error thrown processing message - Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'.
      System.MissingMethodException: Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'.
         at Uno.UI.RemoteControl.Helpers.WebSocketHelper.SendFrame(WebSocket webSocket, Frame frame, CancellationToken ct)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Uno.UI.RemoteControl.Helpers.WebSocketHelper.SendFrame(WebSocket webSocket, Frame frame, CancellationToken ct)
         at Uno.UI.RemoteControl.RemoteControlClient.SendMessage(IMessage message) in /__w/1/s/src/Uno.UI.RemoteControl/RemoteControlClient.cs:line 706
         at Uno.UI.HotDesign.MessageBroker.SendToServerHandler.ProcessMessage(IHotDesignMessage message)
         at Uno.UI.HotDesign.MessageBroker.HandlerQueue.<ProcessQueue>b__19_0()
dbug: Uno.Toolkit.UI.SafeArea[0]
      WindowInsets=[Thickness: 0-0-0-0] bounds=0,0,1011.2000122070312,604.7999877929688 visibleBounds=0,0,1011.2000122070312,604.7999877929688
dbug: Uno.Toolkit.UI.SafeArea[0]
      WindowInsets=[Thickness: 0-0-0-0] bounds=0,0,1011.2000122070312,604.7999877929688 visibleBounds=0,0,1011.2000122070312,604.7999877929688
trce: Uno.UI.Runtime.Skia.Wpf.Rendering.OpenGLWpfRenderer[0]
      Recreate render surface 2528x1512 colorType:Rgba8888 sample:0
trce: Uno.UI.Runtime.Skia.Wpf.Rendering.OpenGLWpfRenderer[0]
      Recreate render surface 2022x1209 colorType:Rgba8888 sample:0
dbug: Uno.Toolkit.UI.SafeArea[0]
      WindowInsets=[Thickness: 0-0-0-0] bounds=0,0,1011,604.5 visibleBounds=0,0,1011,604.5
dbug: Uno.Toolkit.UI.SafeArea[0]
      WindowInsets=[Thickness: 0-0-0-0] bounds=0,0,1011,604.5 visibleBounds=0,0,1011,604.5
dbug: Uno.UI.Xaml.Controls.BaseWindowImplementation[0]
      Window activating with Deactivated state.
dbug: Windows.UI.Core.CoreWindow[0]
      CoreWindow activating with Deactivated state.
```

**Comment by xperiandri** [comment]
How to filter out events correctly?
These make no effect
```
// Uno Platform namespace filter groups
// Uncomment individual methods to see more detailed logging
//// Generic Xaml events
//logBuilder.XamlLogLevel(LogLevel.Debug);
//// Layout specific messages
//logBuilder.XamlLayoutLogLevel(LogLevel.Debug);
//// Storage messages
//logBuilder.StorageLogLevel(LogLevel.Debug);
//// Binding related messages
```
only these work
```
.AddFilter("Microsoft.UI", LogLevel.Critical)
.AddFilter("Uno", LogLevel.Critical)
.AddFilter("Uno.UI.Xaml.Core", LogLevel.Critical)
.AddFilter("Uno.UI.HotDesign", LogLevel.Trace)
```

**Comment by xperiandri** [comment]
@VolodymyrZaburmekha 
> The build of the .slnf file is successful, the build of .sln is not.

this is our solution issue

**Comment by xperiandri** [comment]
When click settings
```
dbug: Windows.UI.Core.CoreWindow[0]
      CoreWindow activating with PointerActivated state.
dbug: Uno.UI.HotDesign.MessageBroker[0]
      Registering handler: 'HotReloadStatusView-sender ()'
trce: Uno.UI.HotDesign.MessageBroker.MessageBrokerRegistration[0]
      HotReloadStatusView-sender sending message: 'LaunchAuthenticationPortalMessage'
warn: Uno.UI.HotDesign.MessageBroker[0]
      Error thrown processing message - Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'.
      System.MissingMethodException: Method not found: 'System.IO.MemoryStream Microsoft.IO.RecyclableMemoryStreamManager.GetStream()'.
         at Uno.UI.RemoteControl.Helpers.WebSocketHelper.SendFrame(WebSocket webSocket, Frame frame, CancellationToken ct)
         at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
         at Uno.UI.RemoteControl.Helpers.WebSocketHelper.SendFrame(WebSocket webSocket, Frame frame, CancellationToken ct)
         at Uno.UI.RemoteControl.RemoteControlClient.SendMessage(IMessage message) in /__w/1/s/src/Uno.UI.RemoteControl/RemoteControlClient.cs:line 706
         at Uno.UI.HotDesign.MessageBroker.SendToServerHandler.ProcessMessage(IHotDesignMessage message)
         at Uno.UI.HotDesign.MessageBroker.HandlerQueue.<ProcessQueue>b__19_0()
dbug: Windows.UI.Core.CoreWindow[0]
      CoreWindow activating with Deactivated state.
dbug: Windows.UI.Core.CoreWindow[0]
      CoreWindow activating with PointerActivated state.
dbug: Windows.UI.Core.CoreWindow[0]
      CoreWindow activating with Deactivated state.
```

**Comment by VolodymyrZaburmekha** [comment]
> > The build of the .slnf file is successful, the build of .sln is not.
> 
> this is our solution issue

I mean maybe because  build of `.sln` is failing it can't do hot reload for some reason

**Comment by DevTKSS** [comment]
@xperiandri would also need that information like you, with the event log to follow up this and other things that should not happen... But to check iut the source of that things which might nor be studio i would like to have some nessaging that is telling me. The logger docs is not really helpful on that as you see

**Comment by DevTKSS** [comment]
@sasakrsmanovic tryed today, as I said, using 5.54+ and desktop only is not having that issue on my side. But I am a bit confused why now theme switching stoped working using the today latest sdk. Updated and created new app and done exactly same code, theme switching not working with same code. I would have send a video but to my own frustration windows decided to just exit the recording without saving or anything after a tutorial video of about 2 h😭 so... All i could share is the old project where those things are working but (no i did not version up in that project) that is the really bad performance one. Bad performance in that way, you are clicking and have to wait for it to react😅 tomorrow will have to do some other stuff will see if i can do another video. So reading here that the uno app is one of many applications so a slnf file is needed, maybe that is the main issue on this and should not be done with studio as target at this point 🤔😅

**Comment by DevTKSS** [comment]
@xperiandri did you try to just dont do that large multi project thing and try if your only target is desktop? As i said: I had this issue with not showing up this settings tab when I targeted windows for example in my case, so i would maybe recommend to try not to target other than this currently recommended one to see if that is Maybe the issue that is the reason for this

**Comment by DevTKSS** [comment]
so update from my side: created new project, using desktop AND Windows target just to test, using uno.sdk 5.5.56 in a regular **Uno App single project**:

- [x] HotReload Performance: no problem, everything smooth as it should be
- [x] Settings showing up to be not set? No settings tab issue showing up!
- [x] Studio Icon showing up and checked to be available (Me beeing in Beta list to meet the requirements for this state): Check, everything fine!
- [x] Intellisense suggesting WindowsAppSDK Resources, also when "just" targeting Desktop: Check => but would not be check if not including win target thats having that package
- [x] Studio Performance: really improved from last versions! Quick and smooth as it should!

Issues I am having: (please tell if I should open issue to that, might be listed)
- deleting things in studio like the stackpanel told from the guide, is not deleting this! resolving in confused Generator engine that is mixing up code where it do not belong!
- NavigationView Settings is not setable (tryed naming the Page to call "MySettingsPage" which should be fine for naming, but could not be found by codebehind ItemInvoked Event calling
```
if(args.IsSettingsInvoked ==true)
{
     this.Navigator()?.NavigateRouteAsync(this, "MySettings", Qualifyers.Nested)
}
``` in studio there is just a textBox to insert something, no idea how Settings could be navigated to using studio? but also no idea with HotReload

**Comment by xperiandri** [comment]
> @xperiandri did you try to just dont do that large multi project thing and try if your only target is desktop?

Yes it works from the template

**Comment by dr1rrb** [comment]
> > @xperiandri did you try to just dont do that large multi project thing and try if your only target is desktop?
> 
> Yes it works from the template. But I need it to work on my solution...

@xperiandri Yes it has to work on any solution even when using a `slnf` file (and even if the `sln` file is broken), that's why I opened an issue, so we are able to track and fix it. But in the meantime, with your fixed `sln` file, does you still have issue or you are able to use the hot-reload?

**Comment by xperiandri** [comment]
What do you mean fixed sln? It was not broken.
No, effect, does not work from SLN

**Comment by dr1rrb** [comment]
@xperiandri oh ok I thought you had issue in your `sln` file due to the conversation you had with @VolodymyrZaburmekha 


>>> The build of the .slnf file is successful, the build of .sln is not.
>>
>> this is our solution issue
>
> I mean maybe because build of `.sln` is failing it can't do hot reload for some reason

I thought you were working on the same project, but I may have misinterpreted the discussion.

Then to help you I need get the content of the "uno Platform" output:

<details>
<summary>Using Visual Studio</summary>

1. Go to _Tools > Options > Projects and Solutions > Build And Run_ and select _Diagnostic_ for the "MSBuild output verbosity"
![image](https://github.com/user-attachments/assets/e2d208af-7588-40d3-8eff-106c1728158a)
2. Restart Visual Studio, re-open your solution and wait for few seconds
3. Go to _View > Output_
4. In the `Output` window select the "Uno Platform" output
![image](https://github.com/user-attachments/assets/b4d87a1b-ce8c-4ad3-b356-a53e191b8561)
</details>

<details>
<summary>Using VS Code</summary>

1. Open you solution in VS code
2. In the status bar at the bottom of the window, make sure to select the `csproj` and "Desktop" platform (cf. [doc](https://platform.uno/docs/articles/create-an-app-vscode.html))
![image](https://github.com/user-attachments/assets/271a45cb-720a-42ea-9b6e-5b973d6ac013)
3. Wait few seconds
4. Go to _View > Output_
5. In the `Output` window select the "Uno Platform - Hot Reload" output
![image](https://github.com/user-attachments/assets/3d207e03-4642-4e7f-806e-6146a466108c)

</details>

**Comment by xperiandri** [comment]
@dr1rrb, nothing interesting
![Image](https://github.com/user-attachments/assets/4e672124-dffa-4016-a052-191d60120446)

```
[ERROR] Value cannot be null.
Parameter name: versionRange
[INFO][16:28:52.12] Uno Remote Control initialized (5.5.95+Branch.release-stable-5.5.Sha.8a86410def5ef6e20cc92f947ea10811e8cceaed.8a86410def5ef6e20cc92f947ea10811e8cceaed)
[INFO] Loaded the Uno.WinUI.DevServer service (5.5.95, API v2).
```

**Comment by TheSameCat2** [comment]
Also facing this issue. 
- Using Visual Studio Code 1.96.4
- Uno Platform plugin 0.19.1
- Uno Platform 5.6.22

Getting this error in the Uno Platform - Hot Reload pane in vscode:
```
[Info] Launching remote control server (Port:53156, Path:C:\Users\nrada\.nuget\packages\uno.winui.devserver\5.5.95\buildTransitive\../tools/rc/host/net9.0/Uno.UI.RemoteControl.Host.dll)
warn: Uno.UI.RemoteControl.Host.Extensibility.AddIns[0]
      Failed to get target frameworks of solution 'C:\Users\nrada\source\repos\TheSameCat2\ScannerDotNet\ScannerDotNet.sln'. This usually indicates that the solution is in an invalid state (e.g. a referenced project is missing on disk). Please fix and restart your IDE (command used: `dotnet build "C:\Users\nrada\source\repos\TheSameCat2\ScannerDotNet\ScannerDotNet.sln" -t:UnoDumpTargetFrameworks "-p:UnoDumpTargetFrameworksTargetFile=C:\Users\nrada\AppData\Local\Temp\tmpv0klt4.tmp" --verbosity quiet`).
```

My target platforms looks like this:
```xml
      <TargetFrameworks>net9.0;</TargetFrameworks>
      <TargetFrameworks Condition=" $([MSBuild]::IsOSPlatform('windows')) ">$(TargetFrameworks);net9.0-desktop;net9.0-windows10.0.26100</TargetFrameworks>
      <TargetFrameworks Condition=" !$([MSBuild]::IsOSPlatform('linux')) ">$(TargetFrameworks);net9.0-maccatalyst</TargetFrameworks>
```

based in part on the documentation [here](https://platform.uno/docs/articles/create-an-app-rider.html?tabs=rider2024-2%2Cdesktop#considerations-for-macos-and-linux)

The application builds and runs great on both platforms (we target macOS and Windows). The settings button does not work on Windows, so I am unable to log in.

**Comment by dr1rrb** [comment]
Hey @TheSameCat2 thanks for the report.

First I notice that the version of the dev-server used is 5.5.95 while you are mentionning that you are using 5.6.22. You should first try to restart your IDE (Ctrl+shift+P / reload window).

If issue persists, we will need you to open a terminal and do the following:

```
cd  "C:\Users\nrada\source\repos\TheSameCat2\ScannerDotNet"
dotnet build "ScannerDotNet.sln" -t:UnoDumpTargetFrameworks "-p:UnoDumpTargetFrameworksTargetFile=C:\Users\nrada\source\repos\TheSameCat2\ScannerDotNet\tfms.txt" --bl:ScannerDotNet.binlog
```

Then if you could send us the `tfms.txt` (if it's being created) and the `ScannerDotNet.binlog` files.

**Comment by dr1rrb** [comment]
> [@dr1rrb](https://github.com/dr1rrb), nothing interesting ![Image](https://github.com/user-attachments/assets/4e672124-dffa-4016-a052-191d60120446)
> 
> ```
> [ERROR] Value cannot be null.
> Parameter name: versionRange
> [INFO][16:28:52.12] Uno Remote Control initialized (5.5.95+Branch.release-stable-5.5.Sha.8a86410def5ef6e20cc92f947ea10811e8cceaed.8a86410def5ef6e20cc92f947ea10811e8cceaed)
> [INFO] Loaded the Uno.WinUI.DevServer service (5.5.95, API v2).
> ```

Hey @xperiandri I think your are not in "diagnostic" verbosity, you should have much more logs, like :

![Image](https://github.com/user-attachments/assets/849f8eef-f9e1-4a0f-9eb5-80e3f4d29177)

Make sure to follow all the steps I put in [my previous message](https://github.com/unoplatform/studio/issues/43#issuecomment-2578821282) for Visual Studio. You can now also find them [in the troubleshoot section here](https://platform.uno/docs/articles/features/working-with-xaml-hot-reload.html?tabs=vswin%2Cwindows%2Cskia-desktop%2Cvswints#troubleshooting)

**Comment by TheSameCat2** [comment]
> Hey [@TheSameCat2](https://github.com/TheSameCat2) thanks for the report.
> 
> First I notice that the version of the dev-server used is 5.5.95 while you are mentionning that you are using 5.6.22. You should first try to restart your IDE (Ctrl+shift+P / reload window).
> 
> If issue persists, we will need you to open a terminal and do the following:

@dr1rrb It did persist. I also rebooted.

> 
> ```
> cd  "C:\Users\nrada\source\repos\TheSameCat2\ScannerDotNet"
> dotnet build "ScannerDotNet.sln" -t:UnoDumpTargetFrameworks "-p:UnoDumpTargetFrameworksTargetFile=C:\Users\nrada\source\repos\TheSameCat2\ScannerDotNet\tfms.txt" --bl:ScannerDotNet.binlog
> ```
> 
> Then if you could send us the `tfms.txt` (if it's being created) and the `ScannerDotNet.binlog` files.

[ScannerDotNet.binlog.txt](https://github.com/user-attachments/files/18680444/ScannerDotNet.binlog.txt) is the only file the command generated. (added .txt to get GitHub to allow its upload)

It failed with:
```
dotnet build "ScannerDotNet.sln" -t:UnoDumpTargetFrameworks "-p:UnoDumpTargetFrameworksTargetFile=C:\Users\nrada\source\repos\TheSameCat2\ScannerDotNet\tfms.txt" --bl:ScannerDotNet.binlog
Restore complete (1.0s)
  ScannerShared failed with 1 error(s) (0.0s)
    C:\Users\nrada\source\repos\TheSameCat2\ScannerDotNet\ScannerShared\ScannerShared.csproj : error MSB4057: The target "UnoDumpTargetFrameworks" does not exist in the project.
  ScannerDotNet.Tests failed with 1 error(s) (0.0s)
    C:\Users\nrada\source\repos\TheSameCat2\ScannerDotNet\ScannerDotNet.Tests\ScannerDotNet.Tests.csproj : error MSB4057: The target "UnoDumpTargetFrameworks" does not exist in the project.
```

The ScannerShared project is a standard .NET9 shared library. I added it. The tests project was added by the template and is unused so far. Both of their target frameworks looks like:
```xml
    <TargetFramework>net9.0</TargetFramework>
```

The

**Comment by dr1rrb** [comment]
Hey @TheSameCat2 interesting issue. Found the reason why you have this, pushing a fix https://github.com/unoplatform/uno/pull/19464

In the meantime, you can add this to your `ScannerShared.csproj` and `ScannerDotNet.Tests.csproj` files to workaround the issue:

```xml
	<Target Name="UnoDumpTargetFrameworks">
		<!--
			This target is used to dump the target frameworks to a temporary file.
			It is useful to determine all target frameworks used by all projects of a solution.
		-->
		<Message Text="&lt;TargetFrameworks&gt;$(TargetFramework);$(TargetFrameworks)&lt;/TargetFrameworks&gt;" Importance="High" />
		<WriteLinesToFile
			Condition="$(UnoDumpTargetFrameworksTargetFile) != ''"
			File="$(UnoDumpTargetFrameworksTargetFile)"
			Lines="$(TargetFramework);$(TargetFrameworks)"
			Overwrite="false"
			Encoding="Unicode"/>
	</Target>

	<Target Name="UnoDumpRemoteControlAddIns">
		<Message Text="&lt;RemoteControlAddIns&gt;@(UnoRemoteControlAddIns)&lt;/RemoteControlAddIns&gt;" Importance="High" />
		<WriteLinesToFile
			Condition="$(UnoDumpRemoteControlAddInsTargetFile) != ''"
			File="$(UnoDumpRemoteControlAddInsTargetFile)"
			Lines="@(UnoRemoteControlAddIns)"
			Overwrite="false"
			Encoding="Unicode"/>
	</Target>
```

**Comment by nickrandolph** [comment]
This issue should be resolved, so closing for now

**Comment by xperiandri** [comment]
What I see now

```
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Exception thrown: 'System.IO.FileNotFoundException' in System.Private.CoreLib.dll
Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor: Trace: ServerMetadataUpdates Enabled:False DebuggerAttached:True BuildingInsideVS: True unorid: Skia
Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor: Trace: Metadata Updates runtime capabilities: Baseline AddMethodToExistingType AddStaticFieldToExistingType AddInstanceFieldToExistingType NewTypeDefinition ChangeCustomAttributes UpdateParameters GenericUpdateMethod GenericAddMethodToExistingType GenericAddFieldToExistingType
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
'Ecierge.Console.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\bin\Debug\net8.0-desktop\Newtonsoft.Json.dll'. Symbol loading disabled by Include/Exclude setting.
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
Exception thrown: 'System.Net.WebSockets.WebSocketException' in System.Private.CoreLib.dll
'Ecierge.Console.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.15\System.Runtime.Serialization.Primitives.dll'. Symbol loading disabled by Include/Exclude setting.
'Ecierge.Console.exe' (CoreCLR: clrhost): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\8.0.15\System.Runtime.Numerics.dll'. Symbol loading disabled by Include/Exclude setting.
'Ecierge.Console.exe' (CoreCLR: clrhost): Loaded 'Anonymously Hosted DynamicMethods Assembly'. 
Uno.UI.RemoteControl.HotReload.ClientHotReloadProcessor: Trace: Successfully sent request to configure HR server for project 'C:\Users\Andrii\Dev\eCierge\PropertyManagement\Console\App\Console.App.csproj'.
Exception thrown: 'System.FormatException' in System.Private.CoreLib.dll
```

**Comment by jeromelaban** [comment]
@xperiandri could you detail a bit more? Let's open another issue with the uno platform VS logs if it's the environment you're running with.

**Comment by xperiandri** [comment]
```
20:35:12.56 Console.App (1): Hot Reload session started.
20:35:53.02 [Error] Exception while emitting update: System.InvalidOperationException: Unexpected null - file EditSession.cs line 697
   at Microsoft.CodeAnalysis.Contract.Fail(String message, Int32 lineNumber, String filePath)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.MergePartialEdits(Compilation oldCompilation, Compilation newCompilation, IReadOnlyList`1 edits, ImmutableArray`1& mergedEdits, ImmutableHashSet`1& addedSymbols, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.GetProjectChangesAsync(ActiveStatementsMap baseActiveStatements, Compilation oldCompilation, Compilation newCompilation, Project oldProject, Project newProject, ImmutableArray`1 changedDocumentAnalyses, CancellationToken cancellationToken)
   at Microsoft.CodeAnalysis.EditAndContinue.EditSession.EmitSolutionUpdateAsync(Solution solution, ActiveStatementSpanProvider solutionActiveStatementSpanProvider, UpdateId updateId, CancellationToken cancellationToken)
20:35:53.23 [Error] C:\Users\Andrii\Dev\eCierge\PropertyManagement\Ecierge.slnx (line 1): error ENC1002: Cannot apply changes -- unexpected error: 'Unexpected null - file EditSession.cs line 697'
20:35:53.27 Invalid changes were found. Please refer to the Error List window to fix those issues.
20:37:21.70 Console.App (1):72368: The process has exited.
20:37:21.70 Console.App (1): Hot Reload session complete.
20:37:30.83 Console.App (2): Hot Reload session started.
```

**Comment by xperiandri** [comment]
So the issue was that some project in the solution do not build.
However the command you execute
```
dotnet build "Project.sln" -t:UnoDumpTargetFrameworks "-p:UnoDumpTargetFrameworksTargetFile=C:\Users\Andrii\AppData\Local\Temp\tmp2dz5t5.tmp" "-p:CustomBeforeMicrosoftCSharpTargets=C:\Users\Andrii\.nuget\packages\uno.winui.devserver\5.6.99\tools\rc\host\net9.0\DevServer.Custom.Targets" --verbosity quiet
```
execute target `UnoDumpTargetFrameworks` that exists only in `Uno.Sdk` and causes the other projects to fail.
It would be nice to fix this too
